// SPDX-License-Identifier: Apache-2.0
#ifndef NATIVE_LDAC_AVRCP_FILTER_IOCTL_H
#define NATIVE_LDAC_AVRCP_FILTER_IOCTL_H

#ifdef _KERNEL_MODE
#include <ntddk.h>
#else
#include <Windows.h>
#include <winioctl.h>
#endif

#define NLD_AVRCP_FILTER_ABI_MAJOR 0u
#define NLD_AVRCP_FILTER_ABI_MINOR 2u
#define FILE_DEVICE_NLD_AVRCP_FILTER 0x8002u

#define IOCTL_NLD_AVRCP_FILTER_GET_VERSION \
    CTL_CODE(FILE_DEVICE_NLD_AVRCP_FILTER, 0x800u, \
             METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_NLD_AVRCP_FILTER_GET_STATUS \
    CTL_CODE(FILE_DEVICE_NLD_AVRCP_FILTER, 0x801u, \
             METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_NLD_AVRCP_FILTER_DEQUEUE_EVENT \
    CTL_CODE(FILE_DEVICE_NLD_AVRCP_FILTER, 0x802u, \
             METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_NLD_AVRCP_FILTER_SET_ABSOLUTE_VOLUME \
    CTL_CODE(FILE_DEVICE_NLD_AVRCP_FILTER, 0x803u, \
             METHOD_BUFFERED, FILE_WRITE_ACCESS)

#define NLD_AVRCP_FILTER_WRITE_ABI_VERSION 1u

#define NLD_AVRCP_FILTER_VERSION_PASS_THROUGH 0x00000001u
#define NLD_AVRCP_FILTER_VERSION_READ_ONLY_CONTROL 0x00000002u
#define NLD_AVRCP_FILTER_VERSION_RAW_PREFIX 0x00000004u
#define NLD_AVRCP_FILTER_VERSION_DEVICE_CONTROL 0x00000008u
#define NLD_AVRCP_FILTER_VERSION_INTERNAL_CONTROL 0x00000010u
#define NLD_AVRCP_FILTER_VERSION_ABSOLUTE_VOLUME_WRITE 0x00000020u

typedef struct _NLD_AVRCP_FILTER_ABI_VERSION {
    ULONG Size;
    ULONG Major;
    ULONG Minor;
    ULONG Flags;
} NLD_AVRCP_FILTER_ABI_VERSION,
  *PNLD_AVRCP_FILTER_ABI_VERSION;

#define NLD_AVRCP_FILTER_STATUS_ONLINE 0x00000001u
#define NLD_AVRCP_FILTER_STATUS_CONTROL_READY 0x00000002u
#define NLD_AVRCP_FILTER_STATUS_QUEUE_OVERFLOW 0x00000004u

typedef struct _NLD_AVRCP_FILTER_STATUS {
    ULONG Size;
    ULONG Flags;
    ULONG QueueDepth;
    ULONG DroppedEvents;
    ULONGLONG NextSequence;
    ULONGLONG NextRequestId;
    ULONGLONG RequestsObserved;
    ULONGLONG CompletionsObserved;
    ULONGLONG CaptureFailures;
    LONG LastCompletionStatus;
    ULONG Reserved;
} NLD_AVRCP_FILTER_STATUS,
  *PNLD_AVRCP_FILTER_STATUS;

typedef struct _NLD_AVRCP_FILTER_SET_VOLUME_REQUEST {
    ULONG Size;
    ULONG Version;
    ULONG Volume;
    ULONG Reserved;
} NLD_AVRCP_FILTER_SET_VOLUME_REQUEST,
  *PNLD_AVRCP_FILTER_SET_VOLUME_REQUEST;

typedef enum _NLD_AVRCP_FILTER_EVENT_TYPE {
    NldAvrcpFilterEventNone = 0,
    NldAvrcpFilterEventLifecycle = 1,
    NldAvrcpFilterEventRequest = 2,
    NldAvrcpFilterEventCompletion = 3,
    NldAvrcpFilterEventCaptureFailure = 4
} NLD_AVRCP_FILTER_EVENT_TYPE;

typedef enum _NLD_AVRCP_FILTER_LIFECYCLE {
    NldAvrcpFilterLifecycleStarted = 1,
    NldAvrcpFilterLifecycleSuspended = 2,
    NldAvrcpFilterLifecycleRestarted = 3,
    NldAvrcpFilterLifecycleCleanup = 4
} NLD_AVRCP_FILTER_LIFECYCLE;

#define NLD_AVRCP_FILTER_EVENT_DEVICE_CONTROL 0x00000001u
#define NLD_AVRCP_FILTER_EVENT_INTERNAL_CONTROL 0x00000002u
#define NLD_AVRCP_FILTER_EVENT_INPUT_PREFIX 0x00000004u
#define NLD_AVRCP_FILTER_EVENT_OUTPUT_PREFIX 0x00000008u
#define NLD_AVRCP_FILTER_EVENT_FORWARD_UNTRACKED 0x00000010u
#define NLD_AVRCP_FILTER_RAW_PREFIX_CAPACITY 32u

typedef struct _NLD_AVRCP_FILTER_EVENT {
    ULONG Size;
    ULONG Type;
    ULONGLONG Sequence;
    ULONGLONG RequestId;
    ULONGLONG Timestamp100ns;
    ULONG Flags;
    ULONG ControlCode;
    ULONG InputSize;
    ULONG OutputSize;
    LONG Status;
    ULONG RawSize;
    ULONGLONG Information;
    UCHAR RawPrefix[NLD_AVRCP_FILTER_RAW_PREFIX_CAPACITY];
} NLD_AVRCP_FILTER_EVENT,
  *PNLD_AVRCP_FILTER_EVENT;

#endif
