// SPDX-License-Identifier: Apache-2.0
#ifndef LDAC_NATIVE_IOCTL_H
#define LDAC_NATIVE_IOCTL_H

#ifdef _KERNEL_MODE
#include <ntddk.h>
#else
#include <Windows.h>
#include <winioctl.h>
#endif

#include <guiddef.h>

/* {C40E5CD8-8C36-4C84-AC21-4A9106C8C655} */
DEFINE_GUID(GUID_DEVINTERFACE_LDAC_NATIVE_TRANSPORT,
            0xc40e5cd8, 0x8c36, 0x4c84,
            0xac, 0x21, 0x4a, 0x91, 0x06, 0xc8, 0xc6, 0x55);

#define LDAC_NATIVE_ABI_MAJOR 0u
#define LDAC_NATIVE_ABI_MINOR 5u

#define FILE_DEVICE_LDAC_NATIVE 0x8000u

#define IOCTL_LDAC_NATIVE_GET_VERSION \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x800u, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_LDAC_NATIVE_GET_DEVICE_INFO \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x801u, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_LDAC_NATIVE_GET_TRANSFER_DIAGNOSTICS \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x802u, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_LDAC_NATIVE_GET_OPEN_DIAGNOSTICS \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x803u, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_LDAC_NATIVE_OPEN_SIGNALING \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x810u, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_LDAC_NATIVE_CLOSE_CHANNELS \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x811u, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_LDAC_NATIVE_WRITE_SIGNALING \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x812u, METHOD_IN_DIRECT, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_LDAC_NATIVE_READ_SIGNALING \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x813u, METHOD_OUT_DIRECT, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_LDAC_NATIVE_OPEN_MEDIA \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x814u, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_LDAC_NATIVE_WRITE_MEDIA \
    CTL_CODE(FILE_DEVICE_LDAC_NATIVE, 0x815u, METHOD_IN_DIRECT, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define LDAC_NATIVE_CHANNEL_DISCONNECTED 0u
#define LDAC_NATIVE_CHANNEL_CONNECTING 1u
#define LDAC_NATIVE_CHANNEL_CONNECTED 2u
#define LDAC_NATIVE_CHANNEL_DISCONNECTING 3u

#define LDAC_NATIVE_DEFAULT_OPEN_TIMEOUT_MS 10000u
#define LDAC_NATIVE_DEFAULT_TRANSFER_TIMEOUT_MS 5000u
#define LDAC_NATIVE_MAX_TIMEOUT_MS 30000u
#define LDAC_NATIVE_MAX_SIGNALING_TRANSFER 4096u
#define LDAC_NATIVE_MAX_MEDIA_TRANSFER 4096u

typedef struct _LDAC_NATIVE_ABI_VERSION {
    ULONG Size;
    ULONG Major;
    ULONG Minor;
    ULONG Flags;
} LDAC_NATIVE_ABI_VERSION;

#define LDAC_NATIVE_DEVICE_INFO_PROFILE_READY 0x00000001u
#define LDAC_NATIVE_DEVICE_INFO_REMOTE_READY 0x00000002u
#define LDAC_NATIVE_DEVICE_INFO_LOCAL_READY 0x00000004u
#define LDAC_NATIVE_DEVICE_INFO_INBOUND_SIGNALING_READY 0x00000008u

typedef struct _LDAC_NATIVE_DEVICE_INFO {
    ULONG Size;
    ULONG Flags;
    ULONGLONG RemoteBluetoothAddress;
    ULONGLONG LocalBluetoothAddress;
    USHORT SignalingPsm;
    USHORT Reserved;
} LDAC_NATIVE_DEVICE_INFO;

typedef struct _LDAC_NATIVE_OPEN_SIGNALING_REQUEST {
    ULONG Size;
    ULONG TimeoutMs;
    USHORT PreferredMtu;
    USHORT Reserved;
} LDAC_NATIVE_OPEN_SIGNALING_REQUEST,
  *PLDAC_NATIVE_OPEN_SIGNALING_REQUEST;

typedef struct _LDAC_NATIVE_CHANNEL_INFO {
    ULONG Size;
    ULONG State;
    USHORT Psm;
    USHORT IncomingMtu;
    USHORT OutgoingMtu;
    USHORT Reserved;
} LDAC_NATIVE_CHANNEL_INFO, *PLDAC_NATIVE_CHANNEL_INFO;

/*
 * READ/WRITE_SIGNALING and WRITE_MEDIA use this structure as the buffered
 * input. The direct output buffer is the transfer buffer in both directions.
 */
typedef struct _LDAC_NATIVE_SIGNALING_TRANSFER_REQUEST {
    ULONG Size;
    ULONG TimeoutMs;
    ULONG Flags;
} LDAC_NATIVE_SIGNALING_TRANSFER_REQUEST,
  *PLDAC_NATIVE_SIGNALING_TRANSFER_REQUEST;

#define LDAC_NATIVE_TRANSFER_OPERATION_NONE 0u
#define LDAC_NATIVE_TRANSFER_OPERATION_READ_SIGNALING 1u
#define LDAC_NATIVE_TRANSFER_OPERATION_WRITE_SIGNALING 2u
#define LDAC_NATIVE_TRANSFER_OPERATION_WRITE_MEDIA 3u

typedef struct _LDAC_NATIVE_TRANSFER_RESULT {
    ULONG Sequence;
    ULONG Operation;
    LONG IoStatus;
    LONG BrbStatus;
    ULONG BtStatus;
    ULONG RequestedBytes;
    ULONG BrbBufferSize;
    ULONG RemainingBytes;
    ULONG TransferFlags;
} LDAC_NATIVE_TRANSFER_RESULT, *PLDAC_NATIVE_TRANSFER_RESULT;

typedef struct _LDAC_NATIVE_TRANSFER_DIAGNOSTICS {
    ULONG Size;
    LDAC_NATIVE_TRANSFER_RESULT Read;
    LDAC_NATIVE_TRANSFER_RESULT Write;
    LDAC_NATIVE_TRANSFER_RESULT MediaWrite;
} LDAC_NATIVE_TRANSFER_DIAGNOSTICS,
  *PLDAC_NATIVE_TRANSFER_DIAGNOSTICS;

#define LDAC_NATIVE_OPEN_OPERATION_NONE 0u
#define LDAC_NATIVE_OPEN_OPERATION_SIGNALING 1u
#define LDAC_NATIVE_OPEN_OPERATION_MEDIA 2u

#define LDAC_NATIVE_OPEN_DIAGNOSTIC_ATTEMPTED 0x00000001u
#define LDAC_NATIVE_OPEN_DIAGNOSTIC_COMPLETED 0x00000002u
#define LDAC_NATIVE_OPEN_DIAGNOSTIC_SUCCEEDED 0x00000004u
#define LDAC_NATIVE_OPEN_DIAGNOSTIC_REMOTE_RESPONSE_VALID 0x00000008u
#define LDAC_NATIVE_OPEN_DIAGNOSTIC_INBOUND_CHANNEL 0x00000010u

/*
 * Records the most recent L2CAP OPEN completion. Response and ResponseStatus
 * are meaningful only when REMOTE_RESPONSE_VALID is set; in that case they
 * are the negative values returned by the remote host, as defined by bthddi.h.
 */
typedef struct _LDAC_NATIVE_OPEN_DIAGNOSTICS {
    ULONG Size;
    ULONG Sequence;
    ULONG Operation;
    LONG IoStatus;
    LONG BrbStatus;
    ULONG BtStatus;
    ULONGLONG RemoteBluetoothAddress;
    ULONG ChannelFlags;
    ULONG Flags;
    USHORT Psm;
    USHORT Response;
    USHORT ResponseStatus;
    USHORT Reserved;
} LDAC_NATIVE_OPEN_DIAGNOSTICS,
  *PLDAC_NATIVE_OPEN_DIAGNOSTICS;

#endif
