// SPDX-License-Identifier: Apache-2.0
#define V1_TRANSPORT_PCM_WORKER 1
#define V1_TRANSPORT_PCM_DURATION_MS 10000u
#define V1_TRANSPORT_PCM_MAXIMUM_GAIN_SCALAR 1.0f
#define V1_TRANSPORT_PCM_MAXIMUM_OUTPUT_PEAK 0.89125094f
#define V1_TRANSPORT_PCM_MAXIMUM_PACKETS 8192u
#define V1_TRANSPORT_PCM_AUDIBLE_PREFLIGHT_TIMEOUT_MS 120000u
#define V1_TRANSPORT_PCM_LINKED_LIMITER 1
#define V1_TRANSPORT_PCM_LIMITER_RELEASE_MS 50.0f
#define V1_TRANSPORT_PCM_SAMPLE_PEAK_FIDELITY 1
#define V1_TRANSPORT_PCM_REQUIRE_STABLE_VOLUME 1
#define V1_TRANSPORT_PCM_FADE_IN_MS 100.0f
#define V1_TRANSPORT_PCM_CEILING_RAMP_START 0.25f
#define V1_TRANSPORT_PCM_CEILING_RAMP_MS 2000.0f
#include "v1_transport_configuration_worker.cpp"
