// SPDX-License-Identifier: Apache-2.0
#define V1_TRANSPORT_PCM_WORKER 1
#define V1_TRANSPORT_PCM_DURATION_MS 60000u
#define V1_TRANSPORT_PCM_MAXIMUM_GAIN_SCALAR 1.0f
#define V1_TRANSPORT_PCM_MAXIMUM_OUTPUT_PEAK 0.25f
#define V1_TRANSPORT_PCM_MAXIMUM_PACKETS 32768u
#define V1_TRANSPORT_PCM_AUDIBLE_PREFLIGHT_TIMEOUT_MS 120000u
#include "v1_transport_configuration_worker.cpp"
