# SPDX-License-Identifier: Apache-2.0
[CmdletBinding()]
param(
    [ValidateSet('Debug', 'Release')]
    [string]$Configuration = 'Release',
    [Guid]$RemoteContainerId = [Guid]::Empty
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-Xm5RemoteContainerId {
    $instancePrefix = 'BTHENUM\{0000110B-0000-1000-8000-00805F9B34FB}_VID&0002054C_PID&0DF0'
    $containerIds = @()
    $devices = @(Get-PnpDevice -ErrorAction Stop)
    foreach ($device in $devices) {
        $instanceId = [string]$device.InstanceId
        if (-not $instanceId.StartsWith(
                $instancePrefix,
                [StringComparison]::OrdinalIgnoreCase)) {
            continue
        }

        $property = Get-PnpDeviceProperty `
            -InstanceId $instanceId `
            -KeyName 'DEVPKEY_Device_ContainerId' `
            -ErrorAction SilentlyContinue
        if ($null -eq $property -or $null -eq $property.Data) {
            continue
        }

        $candidate = [Guid]::Parse([string]$property.Data)
        if ($candidate -ne [Guid]::Empty) {
            $containerIds += $candidate.ToString('D').ToUpperInvariant()
        }
    }

    $uniqueContainerIds = @($containerIds | Sort-Object -Unique)
    if ($uniqueContainerIds.Count -ne 1) {
        throw "Expected exactly one XM5 A2DP Container ID, found $($uniqueContainerIds.Count). Use -RemoteContainerId only after verifying the target device."
    }
    return [Guid]::Parse($uniqueContainerIds[0])
}

function Write-RemoteContainerHeader {
    param(
        [Parameter(Mandatory = $true)]
        [Guid]$ContainerId,
        [Parameter(Mandatory = $true)]
        [string]$Path
    )

    if ($ContainerId -eq [Guid]::Empty) {
        throw 'Refusing to generate a GUID_NULL remote Container ID.'
    }

    $canonical = $ContainerId.ToString('D').ToUpperInvariant()
    $parts = $canonical.Split('-')
    $tail = $parts[3] + $parts[4]
    $formattedBytes = @()
    for ($index = 0; $index -lt 16; $index += 2) {
        $formattedBytes += "0x$($tail.Substring($index, 2).ToLowerInvariant())u"
    }
    $byteInitializer = $formattedBytes -join ', '
    $header = @"
// Generated by tools/build-audio-endpoint.ps1. Do not edit by hand.
#ifndef NATIVE_LDAC_REMOTE_CONTAINER_H
#define NATIVE_LDAC_REMOTE_CONTAINER_H

#include <guiddef.h>

#define NATIVE_LDAC_REMOTE_CONTAINER_ID_STRING \
    "$canonical"

static const GUID NativeLdacRemoteContainerId = {
    0x$($parts[0].ToLowerInvariant())u,
    0x$($parts[1].ToLowerInvariant())u,
    0x$($parts[2].ToLowerInvariant())u,
    { $byteInitializer }
};

#endif
"@
    Set-Content -LiteralPath $Path -Value $header -Encoding Ascii
}

$projectRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$solutionPath = Join-Path $projectRoot 'audio-endpoint\SimpleAudioSample.sln'
$remoteContainerHeader = Join-Path $projectRoot 'audio-endpoint\Source\Inc\nativeldac_remote_container.h'
if ($RemoteContainerId -eq [Guid]::Empty) {
    $RemoteContainerId = Get-Xm5RemoteContainerId
}
Write-RemoteContainerHeader `
    -ContainerId $RemoteContainerId `
    -Path $remoteContainerHeader
Write-Host "Target XM5 Container ID: $($RemoteContainerId.ToString('B').ToUpperInvariant())"
$msbuildCandidates = @(
    'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\MSBuild.exe',
    'C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\MSBuild.exe',
    'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe',
    'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\amd64\MSBuild.exe'
)
$msbuildPath = $msbuildCandidates |
    Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
    Select-Object -First 1
$cmakeCandidates = @(
    'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe',
    'C:\Program Files\CMake\bin\cmake.exe'
)
$cmakePath = $cmakeCandidates |
    Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
    Select-Object -First 1

if (-not $msbuildPath) {
    throw '64-bit Visual Studio 2022 MSBuild was not found.'
}
if (-not (Test-Path -LiteralPath $solutionPath -PathType Leaf)) {
    throw "Audio endpoint solution not found: $solutionPath"
}
if (-not $cmakePath) {
    throw 'CMake was not found for building audio_endpoint_probe.exe.'
}

$driverDate = [DateTime]::UtcNow.ToString(
    'MM/dd/yyyy',
    [Globalization.CultureInfo]::InvariantCulture)
& $msbuildPath $solutionPath /m /t:Rebuild "/p:Configuration=$Configuration" `
    /p:Platform=x64 "/p:NativeLdacDriverDate=$driverDate"
if ($LASTEXITCODE -ne 0) {
    throw "NativeLdacAudio build failed with exit code $LASTEXITCODE."
}

$cmakeBuildRoot = Join-Path $projectRoot 'build\protocol'
$cmakeCache = Join-Path $cmakeBuildRoot 'CMakeCache.txt'
if (-not (Test-Path -LiteralPath $cmakeCache -PathType Leaf)) {
    & $cmakePath -S $projectRoot -B $cmakeBuildRoot -A x64
    if ($LASTEXITCODE -ne 0) {
        throw "CMake configuration failed with exit code $LASTEXITCODE."
    }
}
& $cmakePath --build $cmakeBuildRoot --config $Configuration --target audio_endpoint_probe
if ($LASTEXITCODE -ne 0) {
    throw "audio_endpoint_probe build failed with exit code $LASTEXITCODE."
}

$buildRoot = Join-Path $projectRoot "audio-endpoint\x64\$Configuration"
$sourcePackage = Join-Path $buildRoot 'package'
$certificatePath = Join-Path $buildRoot 'package.cer'
$requiredFiles = @(
    (Join-Path $sourcePackage 'NativeLdacAudio.inf'),
    (Join-Path $sourcePackage 'NativeLdacAudio.sys'),
    (Join-Path $sourcePackage 'NativeLdacAudio.cat'),
    $certificatePath
)
$missingFiles = @($requiredFiles | Where-Object {
    -not (Test-Path -LiteralPath $_ -PathType Leaf)
})
if ($missingFiles.Count -ne 0) {
    throw "Audio endpoint package is incomplete: $($missingFiles -join ', ')"
}

$outputRoot = Join-Path $projectRoot 'artifacts\audio-endpoint'
$outputPackage = Join-Path $outputRoot 'package'
$probeSource = Join-Path $cmakeBuildRoot "$Configuration\audio_endpoint_probe.exe"
$probeOutput = Join-Path $outputRoot 'audio_endpoint_probe.exe'
if (-not (Test-Path -LiteralPath $probeSource -PathType Leaf)) {
    throw "Audio endpoint probe output was not found: $probeSource"
}
New-Item -ItemType Directory -Path $outputPackage -Force | Out-Null
Copy-Item -LiteralPath (Join-Path $sourcePackage 'NativeLdacAudio.inf') -Destination $outputPackage -Force
Copy-Item -LiteralPath (Join-Path $sourcePackage 'NativeLdacAudio.sys') -Destination $outputPackage -Force
Copy-Item -LiteralPath (Join-Path $sourcePackage 'NativeLdacAudio.cat') -Destination $outputPackage -Force
Copy-Item -LiteralPath $certificatePath -Destination (Join-Path $outputPackage 'NativeLdacAudio.cer') -Force
Copy-Item -LiteralPath $probeSource -Destination $probeOutput -Force

$certificate = Get-PfxCertificate -FilePath (Join-Path $outputPackage 'NativeLdacAudio.cer')
$catalogSignature = Get-AuthenticodeSignature -LiteralPath (Join-Path $outputPackage 'NativeLdacAudio.cat')
$driverSignature = Get-AuthenticodeSignature -LiteralPath (Join-Path $outputPackage 'NativeLdacAudio.sys')
if ($null -eq $catalogSignature.SignerCertificate) {
    throw 'NativeLdacAudio.cat does not contain a signer certificate.'
}
if ($catalogSignature.SignerCertificate.Thumbprint -ne $certificate.Thumbprint) {
    throw 'The audio endpoint catalog signer does not match NativeLdacAudio.cer.'
}
if ($null -eq $driverSignature.SignerCertificate) {
    throw 'NativeLdacAudio.sys does not contain a signer certificate.'
}
if ($driverSignature.SignerCertificate.Thumbprint -ne $certificate.Thumbprint) {
    throw 'The audio endpoint driver signer does not match NativeLdacAudio.cer.'
}

$packageFiles = @(Get-ChildItem -LiteralPath $outputPackage -File | Sort-Object Name)
$fileEntries = @($packageFiles | ForEach-Object {
    $hash = Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256
    [ordered]@{
        name = $_.Name
        length = $_.Length
        sha256 = $hash.Hash
    }
})
$manifest = [ordered]@{
    created_at = (Get-Date).ToString('o')
    configuration = $Configuration
    hardware_id = 'ROOT\NativeLdacAudio'
    endpoint_name = 'Native LDAC - WH-1000XM5'
    remote_container_id = $RemoteContainerId.ToString('B').ToUpperInvariant()
    certificate_subject = $certificate.Subject
    certificate_thumbprint = $certificate.Thumbprint
    driver_signature_status = [string]$driverSignature.Status
    catalog_signature_status = [string]$catalogSignature.Status
    probe = [ordered]@{
        name = 'audio_endpoint_probe.exe'
        length = (Get-Item -LiteralPath $probeOutput).Length
        sha256 = (Get-FileHash -LiteralPath $probeOutput -Algorithm SHA256).Hash
    }
    package_files = @($fileEntries)
}
$manifestPath = Join-Path $outputRoot 'manifest.json'
$manifest | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath $manifestPath -Encoding UTF8

Write-Host "Built and staged NativeLdacAudio: $outputPackage"
Write-Host "PCM probe: $probeOutput"
Write-Host "Certificate: $($certificate.Thumbprint)"
Write-Host 'No driver was installed or changed on this computer.'
