// SPDX-License-Identifier: MS-PL
// Portions derived from Microsoft's Windows-driver-samples Bluetooth
// BthEcho sample. Copyright (c) Microsoft Corporation.
#include <initguid.h>
#include "connection.h"
#include <wdmsec.h>

#include "../inc/ldac_native_ioctl.h"

static NTSTATUS LdacNativeRetrieveRemoteAddress(
    _In_ PLDAC_NATIVE_DEVICE_CONTEXT Context);
static NTSTATUS LdacNativeRetrieveLocalAddress(
    _In_ PLDAC_NATIVE_DEVICE_CONTEXT Context);

#ifdef ALLOC_PRAGMA
#pragma alloc_text(PAGE, LdacNativeEvtDeviceAdd)
#pragma alloc_text(PAGE, LdacNativeEvtSelfManagedIoInit)
#pragma alloc_text(PAGE, LdacNativeEvtSelfManagedIoSuspend)
#pragma alloc_text(PAGE, LdacNativeEvtSelfManagedIoRestart)
#pragma alloc_text(PAGE, LdacNativeEvtSelfManagedIoCleanup)
#pragma alloc_text(PAGE, LdacNativeEvtFileCleanup)
#pragma alloc_text(PAGE, LdacNativeEvtDeviceContextCleanup)
#pragma alloc_text(PAGE, LdacNativeEvtIoDeviceControl)
#pragma alloc_text(PAGE, LdacNativeRetrieveRemoteAddress)
#pragma alloc_text(PAGE, LdacNativeRetrieveLocalAddress)
#endif

static NTSTATUS LdacNativeRetrieveRemoteAddress(
    _In_ PLDAC_NATIVE_DEVICE_CONTEXT Context) {
    BTH_DEVICE_INFO deviceInfo;
    WDF_MEMORY_DESCRIPTOR output;
    NTSTATUS status;

    PAGED_CODE();
    RtlZeroMemory(&deviceInfo, sizeof(deviceInfo));
    WDF_MEMORY_DESCRIPTOR_INIT_BUFFER(&output,
                                      &deviceInfo,
                                      sizeof(deviceInfo));
    status = WdfIoTargetSendInternalIoctlSynchronously(
        Context->IoTarget,
        NULL,
        IOCTL_INTERNAL_BTHENUM_GET_DEVINFO,
        NULL,
        &output,
        NULL,
        NULL);
    if (NT_SUCCESS(status)) {
        Context->RemoteAddress = deviceInfo.address;
        Context->InfoFlags |= LDAC_NATIVE_DEVICE_INFO_REMOTE_READY;
    }
    return status;
}

static NTSTATUS LdacNativeRetrieveLocalAddress(
    _In_ PLDAC_NATIVE_DEVICE_CONTEXT Context) {
    struct _BRB_GET_LOCAL_BD_ADDR *brb;
    NTSTATUS status;

    PAGED_CODE();
    brb = (struct _BRB_GET_LOCAL_BD_ADDR *)
        Context->ProfileInterface.BthAllocateBrb(BRB_HCI_GET_LOCAL_BD_ADDR,
                                                LDAC_NATIVE_POOL_TAG);
    if (brb == NULL) return STATUS_INSUFFICIENT_RESOURCES;

    status = LdacNativeSendBrbSynchronously(
        Context,
        (PBRB)brb,
        sizeof(*brb),
        LDAC_NATIVE_DEFAULT_TRANSFER_TIMEOUT_MS);
    if (NT_SUCCESS(status)) {
        Context->LocalAddress = brb->BtAddress;
        Context->InfoFlags |= LDAC_NATIVE_DEVICE_INFO_LOCAL_READY;
    }
    Context->ProfileInterface.BthFreeBrb((PBRB)brb);
    return status;
}

NTSTATUS LdacNativeEvtDeviceAdd(_In_ WDFDRIVER Driver,
                               _Inout_ PWDFDEVICE_INIT DeviceInit) {
    NTSTATUS status;
    WDFDEVICE device;
    WDF_OBJECT_ATTRIBUTES deviceAttributes;
    WDF_OBJECT_ATTRIBUTES requestAttributes;
    WDF_OBJECT_ATTRIBUTES ioRequestAttributes;
    WDF_PNPPOWER_EVENT_CALLBACKS pnpCallbacks;
    WDF_FILEOBJECT_CONFIG fileConfig;
    WDF_OBJECT_ATTRIBUTES fileAttributes;
    WDF_IO_QUEUE_CONFIG queueConfig;
    WDF_OBJECT_ATTRIBUTES queueAttributes;
    PLDAC_NATIVE_DEVICE_CONTEXT context;
    DECLARE_CONST_UNICODE_STRING(sddl,
        L"D:P(A;;GA;;;SY)(A;;GA;;;BA)");

    UNREFERENCED_PARAMETER(Driver);
    PAGED_CODE();

    WdfDeviceInitSetCharacteristics(DeviceInit,
                                    FILE_AUTOGENERATED_DEVICE_NAME,
                                    TRUE);
    status = WdfDeviceInitAssignSDDLString(DeviceInit, &sddl);
    if (!NT_SUCCESS(status)) return status;
    WdfDeviceInitSetDeviceType(DeviceInit, FILE_DEVICE_LDAC_NATIVE);
    WdfDeviceInitSetIoType(DeviceInit, WdfDeviceIoBuffered);
    WdfDeviceInitSetExclusive(DeviceInit, TRUE);

    WDF_FILEOBJECT_CONFIG_INIT(&fileConfig,
                               WDF_NO_EVENT_CALLBACK,
                               WDF_NO_EVENT_CALLBACK,
                               LdacNativeEvtFileCleanup);
    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&fileAttributes,
                                            LDAC_NATIVE_FILE_CONTEXT);
    WdfDeviceInitSetFileObjectConfig(DeviceInit,
                                     &fileConfig,
                                     &fileAttributes);

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(
        &ioRequestAttributes,
        LDAC_NATIVE_BRB_REQUEST_CONTEXT);
    WdfDeviceInitSetRequestAttributes(DeviceInit, &ioRequestAttributes);

    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpCallbacks);
    pnpCallbacks.EvtDeviceSelfManagedIoInit = LdacNativeEvtSelfManagedIoInit;
    pnpCallbacks.EvtDeviceSelfManagedIoSuspend =
        LdacNativeEvtSelfManagedIoSuspend;
    pnpCallbacks.EvtDeviceSelfManagedIoRestart =
        LdacNativeEvtSelfManagedIoRestart;
    pnpCallbacks.EvtDeviceSelfManagedIoCleanup =
        LdacNativeEvtSelfManagedIoCleanup;
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpCallbacks);

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes,
                                            LDAC_NATIVE_DEVICE_CONTEXT);
    deviceAttributes.ExecutionLevel = WdfExecutionLevelPassive;
    deviceAttributes.EvtCleanupCallback =
        LdacNativeEvtDeviceContextCleanup;
    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);
    if (!NT_SUCCESS(status)) return status;

    context = LdacNativeGetDeviceContext(device);
    RtlZeroMemory(context, sizeof(*context));
    context->Device = device;
    context->IoTarget = WdfDeviceGetIoTarget(device);

    status = LdacNativeConnectionInitialize(context);
    if (!NT_SUCCESS(status)) return status;
    context->PnpStarted = FALSE;
    context->ShuttingDown = TRUE;

    status = WdfFdoQueryForInterface(
        device,
        &GUID_BTHDDI_PROFILE_DRIVER_INTERFACE,
        (PINTERFACE)&context->ProfileInterface,
        sizeof(context->ProfileInterface),
        BTHDDI_PROFILE_DRIVER_INTERFACE_VERSION_FOR_QI,
        NULL);
    if (!NT_SUCCESS(status)) return status;
    if (context->ProfileInterface.Interface.InterfaceDereference == NULL) {
        return STATUS_NOINTERFACE;
    }
    context->ProfileInterfaceReferenced = TRUE;
    context->InfoFlags |= LDAC_NATIVE_DEVICE_INFO_PROFILE_READY;

    WDF_OBJECT_ATTRIBUTES_INIT(&requestAttributes);
    requestAttributes.ParentObject = device;
    status = WdfRequestCreate(&requestAttributes,
                              context->IoTarget,
                              &context->InitializationRequest);
    if (!NT_SUCCESS(status)) return status;

    /* AVDTP arms an overlapped read before submitting the matching write.
       Keep cross-direction dispatch parallel; the connection context limits
       each direction to one request and shutdown performs explicit rundown. */
    WDF_IO_QUEUE_CONFIG_INIT_DEFAULT_QUEUE(&queueConfig,
                                           WdfIoQueueDispatchParallel);
    queueConfig.EvtIoDeviceControl = LdacNativeEvtIoDeviceControl;
    WDF_OBJECT_ATTRIBUTES_INIT(&queueAttributes);
    queueAttributes.ExecutionLevel = WdfExecutionLevelPassive;
    status = WdfIoQueueCreate(device,
                              &queueConfig,
                              &queueAttributes,
                              WDF_NO_HANDLE);
    if (!NT_SUCCESS(status)) return status;

    return WdfDeviceCreateDeviceInterface(
        device,
        &GUID_DEVINTERFACE_LDAC_NATIVE_TRANSPORT,
        NULL);
}

VOID LdacNativeEvtDeviceContextCleanup(_In_ WDFOBJECT Object) {
    PLDAC_NATIVE_DEVICE_CONTEXT context =
        LdacNativeGetDeviceContext((WDFDEVICE)Object);
    PINTERFACE_DEREFERENCE dereference;
    PVOID interfaceContext;

    PAGED_CODE();
    if (!context->ProfileInterfaceReferenced) return;
    dereference =
        context->ProfileInterface.Interface.InterfaceDereference;
    interfaceContext = context->ProfileInterface.Interface.Context;
    context->ProfileInterfaceReferenced = FALSE;
    context->InfoFlags &= ~LDAC_NATIVE_DEVICE_INFO_PROFILE_READY;
    RtlZeroMemory(&context->ProfileInterface,
                  sizeof(context->ProfileInterface));
    if (dereference != NULL) dereference(interfaceContext);
}

NTSTATUS LdacNativeEvtSelfManagedIoInit(_In_ WDFDEVICE Device) {
    PLDAC_NATIVE_DEVICE_CONTEXT context = LdacNativeGetDeviceContext(Device);
    NTSTATUS status;

    PAGED_CODE();
    status = LdacNativeRetrieveRemoteAddress(context);
    if (!NT_SUCCESS(status)) return status;
    status = LdacNativeRetrieveLocalAddress(context);
    if (!NT_SUCCESS(status)) return status;

    LdacNativeSetLifecycleState(context, TRUE, FALSE);
    status = LdacNativeRegisterSignalingServer(context);
    if (!NT_SUCCESS(status)) {
        LdacNativeSetLifecycleState(context, FALSE, TRUE);
    }
    return status;
}

NTSTATUS LdacNativeEvtSelfManagedIoSuspend(_In_ WDFDEVICE Device) {
    PLDAC_NATIVE_DEVICE_CONTEXT context = LdacNativeGetDeviceContext(Device);
    NTSTATUS status;

    PAGED_CODE();
    LdacNativeSetLifecycleState(context, FALSE, TRUE);
    status = LdacNativeUnregisterSignalingServer(context, FALSE);
    LdacNativeConnectionShutdown(context);
    WdfWorkItemFlush(context->SignalingServerRundownWorkItem);
    return status;
}

NTSTATUS LdacNativeEvtSelfManagedIoRestart(_In_ WDFDEVICE Device) {
    PLDAC_NATIVE_DEVICE_CONTEXT context = LdacNativeGetDeviceContext(Device);
    NTSTATUS status;

    PAGED_CODE();
    LdacNativeSetLifecycleState(context, TRUE, FALSE);
    status = LdacNativeRegisterSignalingServer(context);
    if (!NT_SUCCESS(status)) {
        LdacNativeSetLifecycleState(context, FALSE, TRUE);
    }
    return status;
}

VOID LdacNativeEvtSelfManagedIoCleanup(_In_ WDFDEVICE Device) {
    PLDAC_NATIVE_DEVICE_CONTEXT context = LdacNativeGetDeviceContext(Device);

    PAGED_CODE();
    LdacNativeSetLifecycleState(context, FALSE, TRUE);
    (void)LdacNativeUnregisterSignalingServer(context, FALSE);
    LdacNativeConnectionShutdown(context);
    WdfWorkItemFlush(context->SignalingServerRundownWorkItem);
}

VOID LdacNativeEvtFileCleanup(_In_ WDFFILEOBJECT FileObject) {
    PLDAC_NATIVE_FILE_CONTEXT fileContext =
        LdacNativeGetFileContext(FileObject);

    PAGED_CODE();
    if (fileContext->OwnsTransport) {
        LdacNativeConnectionShutdown(
            LdacNativeGetDeviceContext(WdfFileObjectGetDevice(FileObject)));
    }
}

VOID LdacNativeEvtIoDeviceControl(_In_ WDFQUEUE Queue,
                                  _In_ WDFREQUEST Request,
                                  _In_ size_t OutputBufferLength,
                                  _In_ size_t InputBufferLength,
                                  _In_ ULONG IoControlCode) {
    WDFDEVICE device = WdfIoQueueGetDevice(Queue);
    PLDAC_NATIVE_DEVICE_CONTEXT context = LdacNativeGetDeviceContext(device);
    WDFFILEOBJECT fileObject = WdfRequestGetFileObject(Request);
    PLDAC_NATIVE_FILE_CONTEXT fileContext =
        fileObject != NULL ? LdacNativeGetFileContext(fileObject) : NULL;
    NTSTATUS status = STATUS_INVALID_DEVICE_REQUEST;
    size_t information = 0u;

    PAGED_CODE();

    if (fileContext != NULL &&
        (IoControlCode == IOCTL_LDAC_NATIVE_OPEN_SIGNALING ||
         IoControlCode == IOCTL_LDAC_NATIVE_CLOSE_CHANNELS ||
         IoControlCode == IOCTL_LDAC_NATIVE_WRITE_SIGNALING ||
         IoControlCode == IOCTL_LDAC_NATIVE_READ_SIGNALING ||
         IoControlCode == IOCTL_LDAC_NATIVE_OPEN_MEDIA ||
         IoControlCode == IOCTL_LDAC_NATIVE_WRITE_MEDIA)) {
        fileContext->OwnsTransport = TRUE;
    }

    if (IoControlCode == IOCTL_LDAC_NATIVE_GET_VERSION) {
        LDAC_NATIVE_ABI_VERSION *version;
        if (OutputBufferLength < sizeof(*version)) {
            status = STATUS_BUFFER_TOO_SMALL;
        } else {
            status = WdfRequestRetrieveOutputBuffer(Request,
                                                    sizeof(*version),
                                                    (PVOID *)&version,
                                                    NULL);
            if (NT_SUCCESS(status)) {
                version->Size = sizeof(*version);
                version->Major = LDAC_NATIVE_ABI_MAJOR;
                version->Minor = LDAC_NATIVE_ABI_MINOR;
                version->Flags = 0u;
                information = sizeof(*version);
            }
        }
    } else if (IoControlCode == IOCTL_LDAC_NATIVE_GET_DEVICE_INFO) {
        LDAC_NATIVE_DEVICE_INFO *info;
        if (OutputBufferLength < sizeof(*info)) {
            status = STATUS_BUFFER_TOO_SMALL;
        } else {
            status = WdfRequestRetrieveOutputBuffer(Request,
                                                    sizeof(*info),
                                                    (PVOID *)&info,
                                                    NULL);
            if (NT_SUCCESS(status)) {
                RtlZeroMemory(info, sizeof(*info));
                info->Size = sizeof(*info);
                info->Flags = context->InfoFlags;
                info->RemoteBluetoothAddress = context->RemoteAddress;
                info->LocalBluetoothAddress = context->LocalAddress;
                info->SignalingPsm = LDAC_NATIVE_AVDTP_PSM;
                information = sizeof(*info);
            }
        }
    } else if (IoControlCode ==
               IOCTL_LDAC_NATIVE_GET_TRANSFER_DIAGNOSTICS) {
        LDAC_NATIVE_TRANSFER_DIAGNOSTICS *diagnostics;
        if (OutputBufferLength < sizeof(*diagnostics)) {
            status = STATUS_BUFFER_TOO_SMALL;
        } else {
            status = WdfRequestRetrieveOutputBuffer(
                Request,
                sizeof(*diagnostics),
                (PVOID *)&diagnostics,
                NULL);
            if (NT_SUCCESS(status)) {
                LdacNativeGetTransferDiagnostics(context, diagnostics);
                information = sizeof(*diagnostics);
            }
        }
    } else if (IoControlCode == IOCTL_LDAC_NATIVE_GET_OPEN_DIAGNOSTICS) {
        LDAC_NATIVE_OPEN_DIAGNOSTICS *diagnostics;
        if (OutputBufferLength < sizeof(*diagnostics)) {
            status = STATUS_BUFFER_TOO_SMALL;
        } else {
            status = WdfRequestRetrieveOutputBuffer(
                Request,
                sizeof(*diagnostics),
                (PVOID *)&diagnostics,
                NULL);
            if (NT_SUCCESS(status)) {
                LdacNativeGetOpenDiagnostics(context, diagnostics);
                information = sizeof(*diagnostics);
            }
        }
    } else if (IoControlCode == IOCTL_LDAC_NATIVE_OPEN_SIGNALING) {
        status = LdacNativeOpenSignaling(context,
                                         Request,
                                         InputBufferLength,
                                         OutputBufferLength);
        if (status == STATUS_PENDING) return;
        if (NT_SUCCESS(status)) {
            information = sizeof(LDAC_NATIVE_CHANNEL_INFO);
        }
    } else if (IoControlCode == IOCTL_LDAC_NATIVE_CLOSE_CHANNELS) {
        status = LdacNativeCloseChannels(
            context,
            LDAC_NATIVE_DEFAULT_TRANSFER_TIMEOUT_MS);
    } else if (IoControlCode == IOCTL_LDAC_NATIVE_WRITE_SIGNALING ||
               IoControlCode == IOCTL_LDAC_NATIVE_READ_SIGNALING) {
        status = LdacNativeTransferSignaling(
            context,
            Request,
            InputBufferLength,
            OutputBufferLength,
            IoControlCode == IOCTL_LDAC_NATIVE_READ_SIGNALING);
        if (status == STATUS_PENDING) return;
    } else if (IoControlCode == IOCTL_LDAC_NATIVE_OPEN_MEDIA) {
        status = LdacNativeOpenMedia(context,
                                     Request,
                                     InputBufferLength,
                                     OutputBufferLength);
        if (status == STATUS_PENDING) return;
    } else if (IoControlCode == IOCTL_LDAC_NATIVE_WRITE_MEDIA) {
        status = LdacNativeWriteMedia(context,
                                      Request,
                                      InputBufferLength,
                                      OutputBufferLength);
        if (status == STATUS_PENDING) return;
    }

    WdfRequestCompleteWithInformation(Request, status, information);
}
